server:
  port: 80

buid.name: ABC Proj
build.version: 0.1


spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/${DB_NAME:abc_tech}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Fiap1234}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

#  security:
#    user:
#      password: xuxuzinho
#      name: admin
#      roles: ADMIN


jwt:
  secret: f1aPs3cr37
  expire: 5