server:
  port: 80

build:
  name: @project.name@
  version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/${DB_NAME:abc_tech}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Fiap1234}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

jwt:
  secret: f1aPs3cr37
  expire: 120000




#  DB_HOSTNAME=db-abc-tech.cnhei6gjxbzn.us-east-1.rds.amazonaws.com
#  DB_PORT=3306
#  DB_NAME=db_abc_tech
#  DB_USERNAME=admin
#  DB_PASSWORD:Fiap1234