server:
  port: 80

buid.name: @project.name@
build.version: @project.version@


spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/${DB_NAME:abc_tech}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Fiap1234}

  jpa:
    hibernate:
      ddl-auto: create
